name: CI # как назвать - выбираете сами
on:
  push:
    branches:
      - master
      - main
jobs:
  build:
    permissions:
      contents: read
      packages: write
    env:
      GHCR_REGISTRY: ghcr.io
      IMAGE: ${{ github.repository }} # docker pull ghcr.io/coursar/frontend:latest
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3 # вытаскиваем из нашего репо исходники
      - run: docker build . -t builder
      - run: docker run -v "$(pwd):/app" builder build
      - uses: actions/upload-artifact@v3
        with:
          name: app.jar
          path: ./target/app.jar